[package]
name = "vyre"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vyre"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream", "gzip"] }
clap = { version = "4", features = ["derive"] }
futures = "0.3"
fake_user_agent = "0.1"
tokio-stream = { version = "0.1", features = ["io-util"] }
anyhow = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
